-- MySQL Script generated by MySQL Workbench
-- Tue Aug 25 13:57:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vista_imobiliaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vista_imobiliaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vista_imobiliaria` DEFAULT CHARACTER SET utf8 ;
USE `vista_imobiliaria` ;

-- -----------------------------------------------------
-- Table `vista_imobiliaria`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vista_imobiliaria`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vista_imobiliaria`.`proprietarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vista_imobiliaria`.`proprietarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(11) NULL,
  `dia_repasse` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vista_imobiliaria`.`imoveis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vista_imobiliaria`.`imoveis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `proprietario_id` INT NOT NULL,
  `cep` VARCHAR(8) NULL,
  `uf` CHAR(2) NOT NULL,
  `cidade` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(100) NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`, `proprietario_id`),
  INDEX `fk_imovel_proprietario_idx` (`proprietario_id` ASC),
  CONSTRAINT `fk_imovel_proprietario`
    FOREIGN KEY (`proprietario_id`)
    REFERENCES `vista_imobiliaria`.`proprietarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vista_imobiliaria`.`contratos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vista_imobiliaria`.`contratos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `proprietario_id` INT NOT NULL,
  `imovel_id` INT NOT NULL,
  `data_inicio` DATETIME NOT NULL,
  `data_fim` DATETIME NOT NULL,
  `dia_vencimento` INT NOT NULL,
  `vigencia` INT NOT NULL,
  `taxa_administracao` DECIMAL(10,2) NOT NULL,
  `valor_aluguel` DECIMAL(10,2) NOT NULL,
  `valor_condominio` DECIMAL(10,2) NULL,
  `valor_iptu` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`, `cliente_id`, `proprietario_id`, `imovel_id`),
  INDEX `fk_contrato_cliente1_idx` (`cliente_id` ASC),
  INDEX `fk_contrato_proprietario1_idx` (`proprietario_id` ASC),
  INDEX `fk_contrato_imovel1_idx` (`imovel_id` ASC),
  CONSTRAINT `fk_contrato_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `vista_imobiliaria`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_proprietario1`
    FOREIGN KEY (`proprietario_id`)
    REFERENCES `vista_imobiliaria`.`proprietarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_imovel1`
    FOREIGN KEY (`imovel_id`)
    REFERENCES `vista_imobiliaria`.`imoveis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vista_imobiliaria`.`mensalidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vista_imobiliaria`.`mensalidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contrato_id` INT NOT NULL,
  `numero_parcela` INT NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mensalidades_contratos1_idx` (`contrato_id` ASC),
  CONSTRAINT `fk_mensalidades_contratos1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `vista_imobiliaria`.`contratos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vista_imobiliaria`.`repasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vista_imobiliaria`.`repasses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contrato_id` INT NOT NULL,
  `numero_parcela` INT NOT NULL,
  `data_vencimento` DATE NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mensalidades_contratos1_idx` (`contrato_id` ASC),
  CONSTRAINT `fk_mensalidades_contratos10`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `vista_imobiliaria`.`contratos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
